version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: userpostgres
      POSTGRES_PASSWORD: passwordpostgres
      POSTGRES_DB: db_postgres
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
